all:
	gcc -o main main.c
	gcc -o fp1 fp1.c 		# function pointer - style 1
	gcc -o struct101 struct101.c 		# How to define a pointer to a structure
	# How to assing array and init it in one line
	gcc -o assignArr assignArr.c 	# this solution compatipile with C11 only.
	gcc -o myInitArr myInitArr.c 	# make your own flexibule version. Wow, this works with any version ..
