all:
	gcc -o fp1.o fp1.c 		# function pointer - style 1
	gcc -o struct101.o struct101.c 		# How to define a pointer to a structure
	# How to assing array and init it in one line
	gcc -o assignArr.o assignArr.c 	# this solution compatipile with C11 only.
	gcc -o myInitArr.o myInitArr.c 	# make your own flexibule version. Wow, this works with any version ..
	gcc -o dynamicArr.o dynamicArr.c # in C, how we manipulat array. but not normal arrays. dynamic alloc arrays.
	gcc -o loop1.o loop1.c # Is there infinite loop with negatives && size_t
	gcc -o do-while-false-trick.o do-while-false-trick.c
	gcc -o macro-fucks-you.o macro-fucks-you.c
	gcc -o double_swap.o double_swap.c
	gcc -o struct-101.o struct-101.c 	# struct - basics
	gcc -o struct-102.o struct-102.c 	# Nested structs
	gcc -o char**.o char**.c 	# What fucking char** means??!!
	gcc -o char**_v2.o char**_v2.c 	# What fucking char** means??!!

